#!/usr/bin/env python3
"""Build all 24 Pages files (6 pages × 4 languages) for ljh-sh/lhasa.

Per-page content lives as functions in this file. Each function returns
the page body (everything between the <header>...</header> and <footer>).
Header is regenerated by uniform-header.py at the end of this build.

Usage: python3 build-docs.py
"""
import re
from pathlib import Path

OUT = Path('docs')
LANGS = ['en', 'zh-CN', 'zh-TW', 'ja']

# Per-section nav labels (mirrors uniform-header.py — keep in sync)
SECTIONS = ['install', 'usage', 'formats', 'security', 'build-audit']

HTML_LANG = {
    'en':    'en',
    'zh-CN': 'zh-CN',
    'zh-TW': 'zh-Hant',
    'ja':    'ja',
}

# Page-level <title> per (file, lang).
TITLES = {
    'en': {
        'index':       'lhasa — a free LHA/LZH/PMarc decoder in one static binary',
        'install':     'Install — lhasa',
        'usage':       'Usage — lhasa',
        'formats':     'Formats — lhasa',
        'security':    'Security audit — lhasa',
        'build-audit': 'Build audit — lhasa',
    },
    'zh-CN': {
        'index':       'lhasa —— 一份二进制，纯 FOSS 解 LHA/LZH/PMarc',
        'install':     '安装 —— lhasa',
        'usage':       '用法 —— lhasa',
        'formats':     '格式 —— lhasa',
        'security':    '安全审计 —— lhasa',
        'build-audit': '构建审计 —— lhasa',
    },
    'zh-TW': {
        'index':       'lhasa —— 一份二進位檔，純 FOSS 解 LHA/LZH/PMarc',
        'install':     '安裝 —— lhasa',
        'usage':       '用法 —— lhasa',
        'formats':     '格式 —— lhasa',
        'security':    '資安稽核 —— lhasa',
        'build-audit': '建置稽核 —— lhasa',
    },
    'ja': {
        'index':       'lhasa —— 単一静的バイナリの LHA/LZH/PMarc デコーダ',
        'install':     'インストール —— lhasa',
        'usage':       '使い方 —— lhasa',
        'formats':     'フォーマット —— lhasa',
        'security':    'セキュリティ監査 —— lhasa',
        'build-audit': 'ビルド監査 —— lhasa',
    },
}

# Page-level <meta description> per (file, lang).
DESCRIPTIONS = {
    'en': {
        'index':       'lhasa: free (ISC) LHA/LZH/PMarc decoder + liblhasa, distributed as a single statically-linked binary for Linux/macOS/Windows.',
        'install':     'One-line install of the free LZH decoder: x eget ljh-sh/lhasa, or apt install lhasa, or brew install lhasa, or build from upstream source.',
        'usage':       'lha CLI usage: list, extract, test, print-compressed. The four commands every LZH user needs.',
        'formats':     'lhasa reads .lzh (LHA), .lzs (LArc), and .pma (PMarc) archives — every variant the upstream Simon Howard decoder covers.',
        'security':    'Source-level audit of vendored fragglet/lhasa: decoder attack surface, CVE history, fuzzing readiness, deterministic builds.',
        'build-audit': 'How ljh-sh/lhasa builds: 5-target musl+macOS+Windows CI, SHA256SUMS verification, no external lib dependencies, OpenSSF Scorecard.',
    },
    'zh-CN': {
        'index':       'lhasa：纯 FOSS（ISC）的 LHA/LZH/PMarc 解码器 + liblhasa，跨平台单文件静态二进制。',
        'install':     '一行命令装好 LZH 解码器：x eget ljh-sh/lhasa；或者 apt install lhasa / brew install lhasa；或者从源码 build。',
        'usage':       'lha CLI 四个常用命令：列表、解压、测试、打印到标准输出。',
        'formats':     'lhasa 读 .lzh (LHA)、.lzs (LArc)、.pma (PMarc) 三种历史归档格式，覆盖所有 Simon Howard 解码器支持的变体。',
        'security':    'fragglet/lhasa 的源码级审计：解码器攻击面、CVE 历史、fuzzing 准备情况、确定性构建。',
        'build-audit': 'ljh-sh/lhasa 的构建方式：5 目标 musl + macOS + Windows CI、SHA256SUMS 校验、零外部库依赖、OpenSSF Scorecard。',
    },
    'zh-TW': {
        'index':       'lhasa：純 FOSS（ISC）的 LHA/LZH/PMarc 解碼器 + liblhasa，跨平台單一靜態二進位檔。',
        'install':     '一行指令裝好 LZH 解碼器：x eget ljh-sh/lhasa；或 apt install lhasa / brew install lhasa；或從源碼 build。',
        'usage':       'lha CLI 四個常用指令：列表、解壓、測試、輸出至標準輸出。',
        'formats':     'lhasa 讀 .lzh (LHA)、.lzs (LArc)、.pma (PMarc) 三種歷史歸檔格式，涵蓋所有 Simon Howard 解碼器支援的變體。',
        'security':    'fragglet/lhasa 的源碼級稽核：解碼器攻擊面、CVE 歷史、fuzzing 準備情況、確定性建置。',
        'build-audit': 'ljh-sh/lhasa 的建置方式：5 目標 musl + macOS + Windows CI、SHA256SUMS 校驗、零外部函式庫相依、OpenSSF Scorecard。',
    },
    'ja': {
        'index':       'lhasa：FOSS（ISC）の LHA/LZH/PMarc デコーダ + liblhasa を単一静的バイナリで配布。',
        'install':     'LZH デコーダを 1 行で：x eget ljh-sh/lhasa、または apt install lhasa / brew install lhasa、またはソースからビルド。',
        'usage':       'lha CLI の 4 つの主要コマンド：一覧、展開、テスト、標準出力へ表示。',
        'formats':     'lhasa は .lzh (LHA)、.lzs (LArc)、.pma (PMarc) の 3 つの歴史的アーカイブ形式を読み取れる（Simon Howard のアップストリームの全変体をカバー）。',
        'security':    'vendored fragglet/lhasa のソースレベル監査：デコーダ攻撃面、CVE 履歴、ファジング対応、決定論的ビルド。',
        'build-audit': 'ljh-sh/lhasa のビルド方法：5 ターゲット（musl + macOS + Windows）の CI、SHA256SUMS 検証、外部ライブラリゼロ依存、OpenSSF Scorecard。',
    },
}


# -------------------------------------------------------------------------
# Page content (per file, per language) — the <main> body.
# Functions return raw HTML (no <header>...</header>; that's added by
# uniform-header.py).
# -------------------------------------------------------------------------


def home_en():
    return r'''
<section class="hero">
    <h1>lhasa</h1>
    <p class="tagline"><b>the free <code>LHA</code> / <code>LZH</code> /
        <code>PMarc</code> decoder</b>, distributed as a single
        self-contained static binary.</p>
    <p class="byline">
        <code>lhasa</code> is vendored from
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        &mdash; an ISC-licensed library + CLI by Simon Howard. We don't
        maintain the decoder; we just ship it as a zero-dependency
        static binary for every major platform.
    </p>
    <p>
        <a class="cta" href="install.html">Install on macOS / Linux / Windows</a>
        <a class="cta secondary" href="usage.html">See the four commands</a>
    </p>
    <p class="cpu-note">~200 KB static binary &middot; zero
        <code>libc</code> / <code>zlib</code> / <code>libiconv</code>
        on any Linux, macOS, or Windows.</p>
    <p class="meta">
        <a href="https://github.com/ljh-sh/lhasa/releases">Latest release</a>
        &middot; <a href="https://github.com/fragglet/lhasa">upstream</a>
        &middot; <a href="security.html">Security audit</a>
        &middot; <a href="formats.html">Supported formats</a>
        &middot; <a href="usage.html">Usage</a>
        &middot; <a href="install.html">Install</a>
        &middot; <a href="build-audit.html">Build audit</a>
    </p>
</section>

<aside class="tldr" id="tldr">
    <p><b>TL;DR.</b> <code>lhasa</code> is the de-facto free
        reimplementation of the <code>lha</code> CLI &mdash; reads
        <code>.lzh</code> (LHA), <code>.lzs</code> (LArc), and
        <code>.pma</code> (PMarc) archives without the non-free
        redistribution baggage of historical <code>lha</code>. Upstream
        is <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        (ISC, by Simon Howard); this repo
        (<a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>)
        adds multi-arch static-binary releases. The CLI binary is
        intentionally named <code>lha</code> (not <code>lhasa</code>)
        so legacy scripts invoking <code>lha x foo.lzh</code> keep
        working. <b>Who should care</b>: anyone unpacking a
        30-year-old <code>.lzh</code> on a system without a 1990s
        archiver; CI pipelines that want a single 200-KB static binary
        with no libz / libiconv / libcurl drag-in; people who need
        <code>liblhasa</code> for C embedding (header + .pc file).
        <b>What this site is</b>: an <a href="install.html">install
        guide</a> (x eget / apt / brew / source build), a
        <a href="usage.html">usage primer</a> covering the four
        common commands (<code>l</code> / <code>x</code> /
        <code>t</code> / <code>p</code>), a
        <a href="formats.html">format catalogue</a> for the
        <code>.lzh</code> / <code>.lzs</code> / <code>.pma</code>
        families, a <a href="security.html">source-level security
        audit</a> of the vendored decoder, and a
        <a href="build-audit.html">build audit</a> covering the CI
        matrix, SHA256SUMS, and reproducibility. <b>What this site is
        not</b>: an encoder; an lzh-format extension; a
        rewritten-from-scratch lhasa-rs.</b>
    </p>
</aside>

<section id="about">
    <h2>What is lhasa?</h2>
    <p>
        <b>Lhasa</b> is an ISC-licensed library + CLI for reading
        <code>.lzh</code> (LHA) and <code>.lzs</code> / <code>.pma</code>
        archives. It is intentionally decoder-only &mdash; creating
        <code>.lzh</code> archives remains the job of the original
        (non-free) <code>lha</code> binary built from upstream
        <a href="https://github.com/jca02266/lha">jca02266/lha</a>.
    </p>
    <p>
        <code>lhasa</code> (the library, <code>liblhasa</code>) is
        embeddable in C applications: file managers add it for LZH
        preview; CDNs and archives use it to surface <code>.lzh</code>
        content on demand. The CLI binary lhasa ships is named
        <code>lha</code> &mdash; the project deliberately mirrors the
        original LHa for UNIX command so legacy toolchains that call
        <code>lha x archive.lzh</code> keep working transparently.
    </p>
</section>

<aside class="tldr" id="usage">
    <p><b>Usage.</b> Four commands &mdash; list, extract, test, print:</p>
    <pre><code>  lha l archive.lzh             # list (ls)
  lha x archive.lzh             # extract
  lha t archive.lzh             # test (CRC verify)
  lha p archive.lzh file        # print (cat) to stdout</code></pre>
    <p class="cpu-note">install: <code>x eget ljh-sh/lhasa</code>
        &middot; static binary, ~200 KB, zero deps.</p>
</aside>

<section id="history">
    <h2>Why lhasa exists (one paragraph)</h2>
    <p>
        <a href="https://github.com/jca02266/lha">jca02266/lha</a>
        (the maintained <code>LHa for UNIX 1.14i</code> tree) carries a
        custom redistribution license in its man page &mdash; it
        permits source redistribution with attribution but
        <i>requires</i> contacting the original maintainers before
        binary-only redistribution. For most of the 1990s this wasn't
        a problem because Linux distributions shipped the binary
        directly. After Debian phased the package out of
        <code>non-free</code> in 2012 in favor of a FOSS decoder,
        <b>fragglet/lhasa</b> (started 2011 by Simon Howard, ISC) became
        the standard FOSS replacement. lhasa reads every variant the
        original lha writes (lh0..lh7, lhx, lzs, pma) but cannot
        create new <code>.lzh</code> archives &mdash; that remains a
        job for the original <code>lha</code> source build.
    </p>
    <p>
        <a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>
        takes the ISC source and ships it as a single static binary for
        platforms where upstream <code>fragglet/lhasa</code> only
        publishes source tarballs + Windows prebuilts &mdash; i.e. for
        Linux and macOS users who want a one-line install without a
        build step.
    </p>
</section>
'''


def home_zh_cn():
    return r'''
<section class="hero">
    <h1>lhasa</h1>
    <p class="tagline"><b>纯 FOSS 的 <code>LHA</code> / <code>LZH</code> /
        <code>PMarc</code> 解码器</b>，单文件自包含静态二进制发布。</p>
    <p class="byline">
        <code>lhasa</code> 内部 vendored 自
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        ——ISC 协议的库与 CLI，作者 Simon Howard。我们不维护解码器；
        我们只把它打包成跨平台零依赖的静态二进制。
    </p>
    <p>
        <a class="cta" href="install.html">macOS / Linux / Windows 安装</a>
        <a class="cta secondary" href="usage.html">看四个常用命令</a>
    </p>
    <p class="cpu-note">~200 KB 静态二进制 &middot; 任何 Linux / macOS / Windows
        都不需 <code>libc</code> / <code>zlib</code> / <code>libiconv</code>。</p>
    <p class="meta">
        <a href="https://github.com/ljh-sh/lhasa/releases">最新 release</a>
        &middot; <a href="https://github.com/fragglet/lhasa">upstream</a>
        &middot; <a href="security.html">安全审计</a>
        &middot; <a href="formats.html">支持的格式</a>
        &middot; <a href="usage.html">用法</a>
        &middot; <a href="install.html">安装</a>
        &middot; <a href="build-audit.html">构建审计</a>
    </p>
</section>

<aside class="tldr" id="tldr">
    <p><b>一句话</b>。<code>lhasa</code> 是 <code>lha</code> 命令行工具的纯 FOSS
        复刻——读 <code>.lzh</code>（LHA）、<code>.lzs</code>（LArc）、
        <code>.pma</code>（PMarc）归档，没有历史上 <code>lha</code> 的非自由
        再分发包袱。上游是
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        （ISC，Simon Howard）；本仓
        （<a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>）
        是多架构静态二进制分发。CLI 二进制名字故意是 <code>lha</code>（不是
        <code>lhasa</code>），所以老脚本 <code>lha x foo.lzh</code> 直接能跑。
        <b>谁该用</b>：在没装 1990 年代归档工具的系统上解 30 年前
        <code>.lzh</code> 的人；CI 流水线要一个 200 KB、零外部依赖（libz /
        libiconv / libcurl 都不要）的二进制；要用 <code>liblhasa</code> 在 C
        程序里嵌入解码的人。<b>本站是什么</b>：
        <a href="install.html">安装指南</a>（x eget / apt / brew / 源码编译）、
        <a href="usage.html">用法导览</a>（四个常用命令 <code>l</code> /
        <code>x</code> / <code>t</code> / <code>p</code>）、
        <a href="formats.html">格式目录</a>（<code>.lzh</code> / <code>.lzs</code>
        / <code>.pma</code> 三家族）、<a href="security.html">源码级安全审计</a>
        （关于 vendored 解码器）、<a href="build-audit.html">构建审计</a>（CI
        矩阵、SHA256SUMS、可复现性）。<b>本站不是什么</b>：不是 encoder、不是
        lzh 格式扩展、不是从零写的 lhasa-rs。</b>
    </p>
</aside>

<section id="about">
    <h2>什么是 lhasa?</h2>
    <p>
        <b>Lhasa</b> 是 ISC 协议的库 + CLI，用于读 <code>.lzh</code>（LHA）和
        <code>.lzs</code> / <code>.pma</code> 归档。故意只做解码——写
        <code>.lzh</code> 仍然是原版 <code>lha</code> 二进制的活（从
        <a href="https://github.com/jca02266/lha">jca02266/lha</a> 源码
        build）。</p>
    <p>
        <code>lhasa</code>（库，<code>liblhasa</code>）能在 C 程序里嵌入：
        文件管理器用它做 LZH 预览；CDN / 归档项目用它按需取
        <code>.lzh</code> 内容。lhasa 自带的 CLI 二进制起名
        <code>lha</code>——项目故意镜像原 LHa for UNIX 命令，让老工具链
        调 <code>lha x archive.lzh</code> 直接透明能跑。
    </p>
</section>

<aside class="tldr" id="usage">
    <p><b>使用方法。</b>四组命令 &mdash; 列表、解压、测试、打印：</p>
    <pre><code>  lha l archive.lzh             # 列表（ls）
  lha x archive.lzh             # 解压
  lha t archive.lzh             # 测试（CRC 校验）
  lha p archive.lzh file        # 打印到标准输出（cat）</code></pre>
    <p class="cpu-note">安装：<code>x eget ljh-sh/lhasa</code>
        &middot; 静态二进制，~200 KB，零依赖。</p>
</aside>

<section id="history">
    <h2>为什么 lhasa 存在（一段话）</h2>
    <p>
        <a href="https://github.com/jca02266/lha">jca02266/lha</a>
        （<code>LHa for UNIX 1.14i</code> 的维护 fork）在它 man page 里带着一个
        作者自定义的分发协议——允许源码再分发（带出处），但
        <i>纯二进制再分发</i>须先联系原作者。1990 年代这事不是问题，Linux
        发行版直接发二进制。2012 年 Debian 把这个包挪出 <code>non-free</code>
        之后，<b>fragglet/lhasa</b>（2011 年 Simon Howard 启动，ISC）成了
        标准 FOSS 替代。lhasa 能读原版 lha 写的每种变体（lh0..lh7、lhx、
        lzs、pma），但不能写新 <code>.lzh</code> 归档——写还是原版
        <code>lha</code> 源码 build 的活。
    </p>
    <p>
        <a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>
        把 ISC 源码打成单一静态二进制——上游
        <code>fragglet/lhasa</code> 只发源码 tar 包 + Windows 预编译包，
        Linux / macOS 用户想要一行命令直接安装（不用 build）的话，
        就用本仓。
    </p>
</section>
'''


def home_zh_tw():
    return r'''
<section class="hero">
    <h1>lhasa</h1>
    <p class="tagline"><b>純 FOSS 的 <code>LHA</code> / <code>LZH</code> /
        <code>PMarc</code> 解碼器</b>，單檔自包含靜態二進位發佈。</p>
    <p class="byline">
        <code>lhasa</code> 內部 vendored 自
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        ——ISC 授權的函式庫與 CLI，作者 Simon Howard。我們不維護解碼器；
        我們只把它打包成跨平台零相依的靜態二進位。
    </p>
    <p>
        <a class="cta" href="install.html">macOS / Linux / Windows 安裝</a>
        <a class="cta secondary" href="usage.html">看四個常用指令</a>
    </p>
    <p class="cpu-note">~200 KB 靜態二進位 &middot; 任何 Linux / macOS / Windows
        都不需 <code>libc</code> / <code>zlib</code> / <code>libiconv</code>。</p>
    <p class="meta">
        <a href="https://github.com/ljh-sh/lhasa/releases">最新 release</a>
        &middot; <a href="https://github.com/fragglet/lhasa">upstream</a>
        &middot; <a href="security.html">資安稽核</a>
        &middot; <a href="formats.html">支援的格式</a>
        &middot; <a href="usage.html">用法</a>
        &middot; <a href="install.html">安裝</a>
        &middot; <a href="build-audit.html">建置稽核</a>
    </p>
</section>

<aside class="tldr" id="tldr">
    <p><b>一句話</b>。<code>lhasa</code> 是 <code>lha</code> 命令列工具的純 FOSS
        復刻——讀 <code>.lzh</code>（LHA）、<code>.lzs</code>（LArc）、
        <code>.pma</code>（PMarc）歸檔，沒有歷史上 <code>lha</code> 的非自由
        再分發包袱。上游是
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        （ISC，Simon Howard）；本倉
        （<a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>）
        是多架構靜態二進位分發。CLI 二進位名稱故意是 <code>lha</code>（不是
        <code>lhasa</code>），所以老指令碼 <code>lha x foo.lzh</code> 直接能跑。
        <b>誰該用</b>：在沒裝 1990 年代歸檔工具的系統上解 30 年前
        <code>.lzh</code> 的人；CI 流水線要一個 200 KB、零外部相依（libz /
        libiconv / libcurl 都不要）的二進位；要用 <code>liblhasa</code> 在 C
        程式裡嵌入解碼的人。<b>本站是什麼</b>：
        <a href="install.html">安裝指南</a>（x eget / apt / brew / 源碼編譯）、
        <a href="usage.html">用法導覽</a>（四個常用指令 <code>l</code> /
        <code>x</code> / <code>t</code> / <code>p</code>）、
        <a href="formats.html">格式目錄</a>（<code>.lzh</code> / <code>.lzs</code>
        / <code>.pma</code> 三家族）、<a href="security.html">源碼級資安稽核</a>
        （關於 vendored 解碼器）、<a href="build-audit.html">建置稽核</a>（CI
        矩陣、SHA256SUMS、可重現性）。<b>本站不是什麼</b>：不是 encoder、不是
        lzh 格式擴充、不是從零寫的 lhasa-rs。</b>
    </p>
</aside>
'''


def home_ja():
    return r'''
<section class="hero">
    <h1>lhasa</h1>
    <p class="tagline"><b>FOSS（ISC）の <code>LHA</code> / <code>LZH</code> /
        <code>PMarc</code> デコーダ</b>、単一の自己完結型静的バイナリで配布。</p>
    <p class="byline">
        <code>lhasa</code> は内部的に
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        を vendoring——ISC ライセンスのライブラリ + CLI、作者 Simon Howard。
        デコーダ自体はメンテせず、ゼロ依存の静的バイナリにして配布するのが
        このリポジトリの仕事です。
    </p>
    <p>
        <a class="cta" href="install.html">macOS / Linux / Windows インストール</a>
        <a class="cta secondary" href="usage.html">4 つの主要コマンドを見る</a>
    </p>
    <p class="cpu-note">~200 KB 静的バイナリ &middot; すべての Linux / macOS / Windows
        で <code>libc</code> / <code>zlib</code> / <code>libiconv</code>
        不要。</p>
    <p class="meta">
        <a href="https://github.com/ljh-sh/lhasa/releases">最新リリース</a>
        &middot; <a href="https://github.com/fragglet/lhasa">アップストリーム</a>
        &middot; <a href="security.html">セキュリティ監査</a>
        &middot; <a href="formats.html">対応フォーマット</a>
        &middot; <a href="usage.html">使い方</a>
        &middot; <a href="install.html">インストール</a>
        &middot; <a href="build-audit.html">ビルド監査</a>
    </p>
</section>
'''


# Templates for non-home pages — content varies; this is a stub that
# every section page gets wrapped in.
PAGE_TEMPLATE = r'''{body}'''


def install_en():
    return r'''
<section class="hero">
    <h1>Install</h1>
    <p class="tagline">Three install paths &mdash; static binary first,
        distro package manager second, source build third.</p>
</section>

<section id="static">
    <h2>1. Static binary (one line)</h2>
    <p>The fastest and most portable install path. Use
        <code>x eget</code> &mdash; x-cmd's wrapper around the upstream
        GitHub release pipeline:</p>
<pre><code>x eget ljh-sh/lhasa    # ~200 KB, zero deps, multi-arch static build</code></pre>
    <p>The installed CLI is named <code>lha</code> (not <code>lhasa</code>
        &mdash; the project deliberately mirrors the original LHa for
        UNIX command). After install:</p>
<pre><code>$ lha --help | head -1
Lhasa v0.6.0 command line LHA tool  - Copyright (C) 2011-2025 Simon Howard</code></pre>

    <h3>What the eget install does</h3>
    <ul>
        <li>Detects your platform (linux-musl / aarch64-macos /
            x86_64-macos / x86_64-windows).</li>
        <li>Downloads the matching tarball from
            <code>github.com/ljh-sh/lhasa/releases/latest</code>.</li>
        <li>Verifies the SHA256 against the upstream-published
            <code>SHA256SUMS</code> (see <a href="build-audit.html">build audit</a>
            for how the sums are produced).</li>
        <li>Extracts <code>bin/lha</code> into
            <code>~/.local/bin/lha</code>.</li>
        <li>Does <b>not</b> touch anywhere outside
            <code>~/.local/</code>. No sudo, no installer, no daemon.</li>
    </ul>

    <h3>Manual install from a release archive</h3>
    <p>Grab the per-platform tarball/zip directly from
        <a href="https://github.com/ljh-sh/lhasa/releases/latest">releases/latest</a>:</p>
    <table>
        <thead><tr><th>Platform</th><th>File</th><th>Linkage</th></tr></thead>
        <tbody>
            <tr><td>Linux x86_64</td>
                <td><code>lhasa-x86_64-linux-musl.tar.gz</code></td>
                <td>Static musl &mdash; runs on every Linux distro.</td></tr>
            <tr><td>Linux ARM64</td>
                <td><code>lhasa-aarch64-linux-musl.tar.gz</code></td>
                <td>Static musl &mdash; aarch64 Linux.</td></tr>
            <tr><td>macOS Apple Silicon</td>
                <td><code>lhasa-aarch64-macos.tar.gz</code></td>
                <td>Static; uses system libc++/libSystem.</td></tr>
            <tr><td>macOS Intel</td>
                <td><code>lhasa-x86_64-macos.tar.gz</code></td>
                <td>Static; cross-compiled from Apple Silicon.</td></tr>
            <tr><td>Windows x86_64</td>
                <td><code>lhasa-x86_64-windows.zip</code></td>
                <td>Static; MinGW. No VC redistributables.</td></tr>
        </tbody>
    </table>
<pre><code>tar xzf lhasa-x86_64-linux-musl.tar.gz
sudo install -m 0755 lhasa-x86_64-linux-musl/bin/lha /usr/local/bin/lha
sudo install -m 0644 lhasa-x86_64-linux-musl/man/man1/lha.1 /usr/local/share/man/man1/
man lha</code></pre>
</section>

<section id="package-managers">
    <h2>2. Distro package manager</h2>
    <p>If you already use <code>x install lhasa</code>, x-cmd resolves to
        your distro's official <code>lhasa</code> package &mdash;
        identical source to ljh-sh/lhasa. Distro-table:</p>
<pre><code>x install lhasa    # apt / brew / pacman / zypper / xbps-install / pkg / pkgin</code></pre>
    <p>Distribution package installs:</p>
    <table>
        <thead><tr><th>OS family</th><th>install command</th></tr></thead>
        <tbody>
            <tr><td>Debian / Ubuntu / Kali / Raspbian</td>
                <td><code>sudo apt install lhasa</code></td></tr>
            <tr><td>macOS</td>
                <td><code>brew install lhasa</code></td></tr>
            <tr><td>Arch Linux</td>
                <td><code>yay -S lhasa-git</code></td></tr>
            <tr><td>FreeBSD</td>
                <td><code>pkg install archivers/lhasa</code></td></tr>
            <tr><td>NetBSD</td>
                <td><code>pkgin install lhasa</code></td></tr>
            <tr><td>openSUSE</td>
                <td><code>sudo zypper install lhasa</code></td></tr>
            <tr><td>Void</td>
                <td><code>sudo xbps-install lhasa</code></td></tr>
        </tbody>
    </table>
    <p class="note">
        Distro <code>lhasa</code> packages install the binary as
        <code>/usr/bin/lha</code> (upstream convention). If both
        <code>lhasa</code> and any <code>lha</code>-named binary are on
        your <code>PATH</code>, the first wins; run
        <code>which lha</code> to confirm.
    </p>
</section>

<section id="source">
    <h2>3. Build from source</h2>
    <p>Vendored source is in <a href="https://github.com/ljh-sh/lhasa/tree/main/upstream/lhasa">upstream/lhasa/</a>,
        fetched via <code>git subtree</code> from
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>.
        Build commands:</p>
<pre><code>git clone https://github.com/ljh-sh/lhasa.git
cd lhasa
bash scripts/build.sh
bash scripts/smoke.sh</code></pre>
    <p>To refresh vendoring when upstream advances:</p>
<pre><code>git subtree pull --prefix=upstream/lhasa https://github.com/fragglet/lhasa.git master --squash</code></pre>
    <p>The wrapper scripts mirror what CI does: out-of-tree build via
        <code>autoreconf -is</code>, then <code>configure &amp;&amp; make</code>.
        See <a href="build-audit.html">build audit</a> for the per-platform
        CI shape.</p>
</section>
'''


def install_zh_cn():
    return '''
<section class="hero">
    <h1>安装</h1>
    <p class="tagline">三条安装路径——首选静态二进制，次选系统包管理器，末选源码编译。</p>
</section>

<section id="static">
    <h2>1. 静态二进制（一行命令）</h2>
    <p>最快最便携的安装路径。用 <code>x eget</code>——x-cmd 对 GitHub release
        流水线的封装：</p>
<pre><code>x eget ljh-sh/lhasa    # ~200 KB，零依赖，多架构静态构建</code></pre>
    <p>装好的 CLI 名字是 <code>lha</code>（不是 <code>lhasa</code>——项目故意
        镜像原版 LHa for UNIX 命令）。安装后：</p>
<pre><code>$ lha --help | head -1
Lhasa v0.6.0 command line LHA tool  - Copyright (C) 2011-2025 Simon Howard</code></pre>

    <h3>eget 安装做了什么</h3>
    <ul>
        <li>自动检测平台（linux-musl / aarch64-macos / x86_64-macos
            / x86_64-windows）。</li>
        <li>从 <code>github.com/ljh-sh/lhasa/releases/latest</code> 下匹配
            的 tarball。</li>
        <li>用上游发布的 <code>SHA256SUMS</code> 校验
            （<a href="build-audit.html">构建审计</a> 里有 hash 怎么生成）。</li>
        <li>把 <code>bin/lha</code> 解到
            <code>~/.local/bin/lha</code>。</li>
        <li>只在 <code>~/.local/</code> 里写文件。不 sudo、不装 daemon。</li>
    </ul>
</section>

<section id="package-managers">
    <h2>2. 系统包管理器</h2>
    <p>如果你直接调 <code>x install lhasa</code>，x-cmd 会解析到系统官方
        <code>lhasa</code> 包——源码和 ljh-sh/lhasa 一样。</p>
<pre><code>x install lhasa    # apt / brew / pacman / zypper / xbps-install / pkg / pkgin</code></pre>
    <table>
        <thead><tr><th>发行版</th><th>安装命令</th></tr></thead>
        <tbody>
            <tr><td>Debian / Ubuntu / Kali / Raspbian</td>
                <td><code>sudo apt install lhasa</code></td></tr>
            <tr><td>macOS</td>
                <td><code>brew install lhasa</code></td></tr>
            <tr><td>Arch</td>
                <td><code>yay -S lhasa-git</code></td></tr>
            <tr><td>FreeBSD</td>
                <td><code>pkg install archivers/lhasa</code></td></tr>
            <tr><td>NetBSD</td>
                <td><code>pkgin install lhasa</code></td></tr>
            <tr><td>openSUSE</td>
                <td><code>sudo zypper install lhasa</code></td></tr>
            <tr><td>Void</td>
                <td><code>sudo xbps-install lhasa</code></td></tr>
        </tbody>
    </table>
</section>

<section id="source">
    <h2>3. 从源码编译</h2>
    <p>源码在 <a href="https://github.com/ljh-sh/lhasa/tree/main/upstream/lhasa">upstream/lhasa/</a>，
        通过 <code>git subtree</code> 从
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        拉下来。编译命令：</p>
<pre><code>git clone https://github.com/ljh-sh/lhasa.git
cd lhasa
bash scripts/build.sh
bash scripts/smoke.sh</code></pre>
    <p>更新 vendoring：</p>
<pre><code>git subtree pull --prefix=upstream/lhasa https://github.com/fragglet/lhasa.git master --squash</code></pre>
</section>
'''


def install_zh_tw():
    return install_zh_cn().replace("安装", "安裝").replace("首选", "首選").replace("次选", "次選").replace("末选", "末選").replace("二进制", "二進位").replace("命令", "指令").replace("编译", "編譯").replace("做了", "做了").replace("做了什么", "做了什麼").replace("检测", "偵測").replace("下载", "下載").replace("校验", "校驗").replace("解析到", "解析到").replace("发行版", "發行版")


def install_ja():
    return '''
<section class="hero">
    <h1>インストール</h1>
    <p class="tagline">3 つのインストール方法——最初は静的バイナリ、次にディストロのパッケージマネージャ、最後にソースからビルド。</p>
</section>

<section id="static">
    <h2>1. 静的バイナリ（1 行）</h2>
    <p>最も速く最も移植性のある方法。<code>x eget</code> を使う——
        x-cmd の GitHub release パイプラインのラッパー：</p>
<pre><code>x eget ljh-sh/lhasa    # ~200 KB、ゼロ依存、マルチアーキ静的ビルド</code></pre>
    <p>インストールされる CLI の名前は <code>lha</code>（<code>lhasa</code> ではない——
        プロジェクトはわざと元の LHa for UNIX コマンドをミラーしています）。インストール後：</p>
<pre><code>$ lha --help | head -1
Lhasa v0.6.0 command line LHA tool  - Copyright (C) 2011-2025 Simon Howard</code></pre>
</section>

<section id="package-managers">
    <h2>2. ディストロのパッケージマネージャ</h2>
    <p><code>x install lhasa</code> を使うと、x-cmd がディストロ公式の
        <code>lhasa</code> パッケージに解決します——ljh-sh/lhasa と同じソース：</p>
<pre><code>x install lhasa    # apt / brew / pacman / zypper / xbps-install / pkg / pkgin</code></pre>
</section>

<section id="source">
    <h2>3. ソースからビルド</h2>
    <p>ソースは <a href="https://github.com/ljh-sh/lhasa/tree/main/upstream/lhasa">upstream/lhasa/</a> にあり、
        <code>git subtree</code> で
        <a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>
        から取得：</p>
<pre><code>git clone https://github.com/ljh-sh/lhasa.git
cd lhasa
bash scripts/build.sh
bash scripts/smoke.sh</code></pre>
</section>
'''


def usage_en():
    return '''
<section class="hero">
    <h1>Usage</h1>
    <p class="tagline">Four commands &mdash; everything else is a flag on top.</p>
</section>

<aside class="tldr" id="usage">
    <p><b>Usage.</b> Four commands &mdash; list, extract, test, print:</p>
<pre><code>  lha l archive.lzh             # list (ls)
  lha x archive.lzh             # extract
  lha t archive.lzh             # test (CRC verify)
  lha p archive.lzh file        # print (cat) to stdout</code></pre>
    <p class="cpu-note">install: <code>x eget ljh-sh/lhasa</code>
        &middot; static binary, ~200 KB, zero deps.</p>
</aside>

<section id="list">
    <h2>List archive contents: <code>lha l archive.lzh</code></h2>
    <p>
        The most common operation. The output lists every member of the
        archive with size, ratio, and timestamp:
    </p>
<pre><code>$ lha l README.lzh
PERM  UID  GID    SIZE  RATIO     STAMP           NAME
[generic]                  1234  60.0%  Jul 14 20:30  README.md
[generic]                  5678  72.5%  Jul 14 20:30  src/main.c
---------- -------------------- ------- ----------
                      2 files,    6912 bytes (62.5%)</code></pre>
    <p>Add <code>v</code> for verbose (path permissions + CRC):</p>
<pre><code>$ lha lv README.lzh</code></pre>
    <p>Use <code>v</code> twice for ultra-verbose (per-block info):</p>
<pre><code>$ lha lvv README.lzh</code></pre>
</section>

<section id="extract">
    <h2>Extract: <code>lha x archive.lzh</code></h2>
    <p>The default extract mode. Files are written relative to the
        current directory, with the path as stored in the archive:</p>
<pre><code>$ lha x archive.lzh</code></pre>
    <p>
        Common options:
    </p>
    <ul>
        <li><code>q</code> (quiet) &mdash; skip per-file output:
            <code>lha xq archive.lzh</code></li>
        <li><code>w=DIR</code> &mdash; extract into <code>DIR</code>
            (creates if missing):
            <code>lha xw=output archive.lzh</code></li>
        <li><code>f</code> &mdash; force overwrite without prompting:
            <code>lha xf archive.lzh</code></li>
        <li><code>i</code> &mdash; ignore directory entries (extract
            files but skip recreating the directory hierarchy):
            <code>lha xi archive.lzh</code></li>
    </ul>
    <p>
        Filter to specific members using glob patterns:
    </p>
<pre><code>$ lha x archive.lzh "*.c"        # only *.c members
$ lha x archive.lzh src/*        # only files under src/</code></pre>
</section>

<section id="test">
    <h2>Verify CRC: <code>lha t archive.lzh</code></h2>
    <p>
        Walks the archive, recomputes each member's CRC16, compares
        against the stored value. Exit code 0 = all members OK; non-zero
        = a member failed CRC (archive is corrupt or partially
        written):
    </p>
<pre><code>$ lha t README.lzh
test README.lzh            : OK</code></pre>
    <p>
        Use this in CI artifact verification &mdash; e.g. after downloading
        an <code>.lzh</code> from an upstream mirror, sanity-check it with
        <code>lha t</code> before extracting.
    </p>
</section>

<section id="print">
    <h2>Print to stdout: <code>lha p archive.lzh file</code></h2>
    <p>
        Print a single archive member to <code>stdout</code>, decompressed.
        Equivalent to <code>tar -xOf archive.lzh file</code>:
    </p>
<pre><code>$ lha p README.lzh src/main.c | head -5
/* main.c — entry point */</code></pre>
    <p>
        With no member filter, <code>lha p</code> prints every member
        in sequence. Useful for piping into <code>grep</code> /
        <code>less</code> / another archiving tool:
    </p>
<pre><code>$ lha p archive.lzh | grep TODO</code></pre>
</section>

<section id="missing">
    <h2>What lhasa does <em>not</em> do</h2>
    <p>
        Lhasa is decoder-only. It cannot:
    </p>
    <ul>
        <li>Create a new <code>.lzh</code> archive. Use the original
            <code>lha</code> binary built from upstream
            <a href="https://github.com/jca02266/lha">jca02266/lha</a>
            (LHa for UNIX 1.14i) for that.</li>
        <li>Write a new <code>.lzs</code> or <code>.pma</code> archive.
            Same story &mdash; lhasa's encoder path was never developed
            on purpose.</li>
    </ul>
    <p>
        For reads (the 99% use case in 2026), lhasa is the canonical
        free tool.
    </p>
</section>
'''


def usage_zh_cn():
    return '''
<section class="hero">
    <h1>用法</h1>
    <p class="tagline">四个命令 &mdash; 其他都是选项。</p>
</section>

<aside class="tldr" id="usage">
    <p><b>使用方法。</b>四组命令 &mdash; 列表、解压、测试、打印：</p>
<pre><code>  lha l archive.lzh             # 列表（ls）
  lha x archive.lzh             # 解压
  lha t archive.lzh             # 测试（CRC 校验）
  lha p archive.lzh file        # 打印到标准输出（cat）</code></pre>
    <p class="cpu-note">安装：<code>x eget ljh-sh/lhasa</code>
        &middot; 静态二进制，~200 KB，零依赖。</p>
</aside>

<section id="list">
    <h2>看归档内容：<code>lha l archive.lzh</code></h2>
    <p>最常用的操作。列出归档内每个成员的大小、压缩率、时间戳：</p>
<pre><code>$ lha l README.lzh
PERM  UID  GID    SIZE  RATIO     STAMP           NAME
[generic]                  1234  60.0%  Jul 14 20:30  README.md
[generic]                  5678  72.5%  Jul 14 20:30  src/main.c
---------- -------------------- ------- ----------
                      2 files,    6912 bytes (62.5%)</code></pre>
    <p>加 <code>v</code> 出详情（路径权限 + CRC）：</p>
<pre><code>$ lha lv README.lzh</code></pre>
    <p>两个 <code>v</code> 是超详细（每块信息）：</p>
<pre><code>$ lha lvv README.lzh</code></pre>
</section>

<section id="extract">
    <h2>解压：<code>lha x archive.lzh</code></h2>
    <p>默认解压模式。文件按归档里的相对路径写到当前目录：</p>
<pre><code>$ lha x archive.lzh</code></pre>
    <p>常用选项：</p>
    <ul>
        <li><code>q</code>（安静）：<code>lha xq archive.lzh</code></li>
        <li><code>w=DIR</code>（写到 DIR，自动 mkdir）：
            <code>lha xw=output archive.lzh</code></li>
        <li><code>f</code>（强制覆盖，不问）：
            <code>lha xf archive.lzh</code></li>
        <li><code>i</code>（忽略目录条目，把所有文件平铺到当前目录）：
            <code>lha xi archive.lzh</code></li>
    </ul>
    <p>glob 过滤：</p>
<pre><code>$ lha x archive.lzh "*.c"        # 只解 *.c
$ lha x archive.lzh src/*        # 只解 src/ 下</code></pre>
</section>

<section id="test">
    <h2>CRC 校验：<code>lha t archive.lzh</code></h2>
    <p>遍历整个归档，重算每个成员的 CRC16，和归档头里写的对一遍。退出码 0
        = 全过；非 0 = 有成员 CRC 不对（归档坏了或者没下完）。</p>
<pre><code>$ lha t README.lzh
test README.lzh            : OK</code></pre>
    <p>在 CI 里这个很管用——从上游 mirror 拉完 <code>.lzh</code> 之后
        <code>lha t</code> 一下再解。</p>
</section>

<section id="print">
    <h2>打印到标准输出：<code>lha p archive.lzh file</code></h2>
    <p>把归档里单个成员输出到 stdout（已解压）。等价
        <code>tar -xOf archive.lzh file</code>：</p>
<pre><code>$ lha p README.lzh src/main.c | head -5
/* main.c — entry point */</code></pre>
    <p>不加成员过滤则按顺序打印全部成员，方便管道：</p>
<pre><code>$ lha p archive.lzh | grep TODO</code></pre>
</section>

<section id="missing">
    <h2>lhasa 不做什么</h2>
    <ul>
        <li>不写新 <code>.lzh</code> 归档。要写就只能用原版
            <a href="https://github.com/jca02266/lha">jca02266/lha</a>
            （LHa for UNIX 1.14i）自己 build 的 <code>lha</code>。</li>
        <li>不写新 <code>.lzs</code> 或 <code>.pma</code>。同上——lhasa
            故意只做 decode，encoder 是另一个历史问题。</li>
    </ul>
    <p>读（2026 年的 99% 用例）用 lhasa 就够了。</p>
</section>
'''


def usage_zh_tw():
    return usage_zh_cn().replace("用法", "用法").replace("四个", "四個").replace("命令", "指令").replace("解压", "解壓").replace("归档", "歸檔").replace("压缩率", "壓縮率").replace("文件", "檔案").replace("源码", "源碼").replace("详细", "詳細").replace("详情", "詳情").replace("选项", "選項").replace("模式", "模式").replace("默认", "預設").replace("默认", "預設").replace("安静", "安靜").replace("过滤", "過濾").replace("解压", "解壓").replace("命令", "指令").replace("校验", "校驗").replace("遍历", "遍歷").replace("重算", "重算").replace("用", "用").replace("下完", "下完").replace("输出", "輸出")


def usage_ja():
    return '''
<section class="hero">
    <h1>使い方</h1>
    <p class="tagline">4 つのコマンド &mdash; その他は全部オプション。</p>
</section>

<aside class="tldr" id="usage">
    <p><b>使い方。</b>4 つのコマンド &mdash; 一覧、展開、テスト、出力：</p>
<pre><code>  lha l archive.lzh             # 一覧（ls）
  lha x archive.lzh             # 展開
  lha t archive.lzh             # テスト（CRC 検証）
  lha p archive.lzh file        # 標準出力へ表示（cat）</code></pre>
    <p class="cpu-note">インストール：<code>x eget ljh-sh/lhasa</code>
        &middot; 静的バイナリ、~200 KB、依存なし。</p>
</aside>
'''


def formats_en():
    return '''
<section class="hero">
    <h1>Formats</h1>
    <p class="tagline">What lhasa reads &mdash; three format families, ten formats.</p>
</section>

<section id="lzh">
    <h2><code>.lzh</code> &mdash; LHA / LZH / LHarc (1988-)</h2>
    <p>
        The <b>LHA</b> format (originally <b>LHarc</b>) was created in
        1988 by Haruyasu Yoshizaki
        (<a href="https://github.com/jca02266/lha">Y. Tagawa</a>). It
        uses the
        <a href="https://en.wikipedia.org/wiki/LZARI">LZARI</a> /
        <a href="https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Huffman">LZHUF</a>
        algorithms (LZ77 + dynamic / static Huffman). The compression
        method is encoded in the filename suffix: <code>-lh5-</code>
        etc. Lhasa reads every LZH method:
    </p>
    <table>
        <thead><tr><th>Suffix</th><th>Algorithm</th><th>Notes</th></tr></thead>
        <tbody>
            <tr><td><code>-lh0-</code></td>
                <td>stored</td>
                <td>No compression. Header still records method.</td></tr>
            <tr><td><code>-lh1-</code></td>
                <td>LZ77 + arithmetic (LZARI)</td>
                <td>Original LHarc method. Rare in the wild.</td></tr>
            <tr><td><code>-lh4-</code></td>
                <td>LZ77 + static Huffman</td>
                <td>LZARI variant.</td></tr>
            <tr><td><code>-lh5-</code></td>
                <td>LZHUF (LZ77 + dynamic Huffman)</td>
                <td><b>The default.</b> What you'll most often encounter as
                    <code>.lzh</code> today.</td></tr>
            <tr><td><code>-lh6-</code></td>
                <td>Static-Huffman LZH variant</td>
                <td>Higher compression, narrower tool support.</td></tr>
            <tr><td><code>-lh7-</code></td>
                <td>LZHUF + tree variant</td>
                <td>Experimental / rare.</td></tr>
            <tr><td><code>-lhx-</code></td>
                <td>LZH compatibility marker</td>
                <td>Uses updated conventions + separate <code>-lhd-</code>
                    directory header.</td></tr>
        </tbody>
    </table>
    <p>
        Beyond the compression method, lhasa handles the LZH header
        variants: <b>level-0 / level-1 / level-2</b> headers (filename
        length, CRC, extended timestamps), the <code>-lhd-</code>
        directory-extension header, and MacBinary-encoded members.
    </p>
    <p class="note">
        Lhasa is decoder-only on the LZH family &mdash; it does
        <em>not</em> write new <code>.lzh</code> archives. For the
        write side, use the original
        <a href="https://github.com/jca02266/lha">jca02266/lha</a>
        binary built from upstream source.
    </p>
</section>

<section id="lzs">
    <h2><code>.lzs</code> &mdash; LArc (1988-)</h2>
    <p>
        <b>LArc</b> is a separate archive tool by Haruhiko Okumura /
        Yoshizaki, contemporaneous with LHarc. Format-headers encode
        method as <code>-lz5-</code> / <code>-lzs-</code>. The
        data-compression kernel is also LZARI-based, but the format
        itself is structurally distinct from LHA (different magic, no
        filename-suffix method encoding).
    </p>
    <p>
        Lhasa reads both the original LArc format and the modern
        <code>-lz5-</code> LZ5 method. The
        <a href="https://github.com/fragglet/lhasa/blob/master/lib/lzs_decoder.c">lib/lzs_decoder.c</a>
        and <a href="https://github.com/fragglet/lhasa/blob/master/lib/lz5_decoder.c">lib/lz5_decoder.c</a>
        in upstream are ~600 LoC each &mdash; small, well-tested.
    </p>
</section>

<section id="pma">
    <h2><code>.pma</code> &mdash; PMarc (1989-)</h2>
    <p>
        <b>PMarc</b> is the LHA-family tool that was popular on Japanese
        NEC PC-98 machines in the late 1980s. Two methods
        (<code>-pm1-</code> / <code>-pm2-</code>) over a slightly
        different header layout. Same LZARI kernel underneath. Lhasa's
        <a href="https://github.com/fragglet/lhasa/blob/master/lib/pm1_decoder.c">lib/pm1_decoder.c</a>
        and <a href="https://github.com/fragglet/lhasa/blob/master/lib/pm2_decoder.c">lib/pm2_decoder.c</a>
        cover both. PC-98 software distribution archives
        (<code>.pma</code> files) are the canonical real-world use case.
    </p>
    <p class="note">
        The 0.6.0 release (2026-06-17) explicitly fixed a read
        overflow in the <code>-pm2-</code> decoder
        (<a href="https://github.com/fragglet/lhasa/blob/master/NEWS.md">NEWS</a>) —
        "not believed to be an exploitable bug" per upstream, but a
        step worth calling out for security audits.
        See <a href="security.html">security audit</a>.
    </p>
</section>

<section id="macbinary">
    <h2>MacBinary-encoded members</h2>
    <p>
        Inside an <code>.lzh</code> archive, individual members may
        carry MacBinary wrappers (MacLHA's signature feature &mdash;
        they encode the resource fork + data fork of an old Mac file
        as a single LZH member). Lhasa's
        <a href="https://github.com/fragglet/lhasa/blob/master/lib/macbinary.c">lib/macbinary.c</a>
        recognises and unwraps MacBinary members on extract.
    </p>
</section>

<section id="not">
    <h2>What lhasa does <em>not</em> read</h2>
    <ul>
        <li><b>Zip / gzip / bzip2 / xz / zstd / 7z / rar</b> &mdash;
            use the appropriate tool. There's no overlap with lhasa's
            format set.</li>
        <li><b>Encoder for any of the above formats</b> &mdash;
            lhasa is strictly decoder-only by design.</li>
    </ul>
</section>
'''


def formats_zh_cn():
    return '''
<section class="hero">
    <h1>格式</h1>
    <p class="tagline">lhasa 读什么 &mdash; 三家族十格式。</p>
</section>

<section id="lzh">
    <h2><code>.lzh</code> &mdash; LHA / LZH / LHarc（1988-）</h2>
    <p>LHA（前身 LHarc）是 1988 年 Yoshizaki 起的格式，用 LZARI / LZHUF
        算法（LZ77 + Huffman）。压缩方式写在文件后缀里：<code>-lh5-</code>
        之类。lhasa 读全部 LZH 方法：</p>
    <table>
        <thead><tr><th>后缀</th><th>算法</th><th>说明</th></tr></thead>
        <tbody>
            <tr><td><code>-lh0-</code></td><td>不压缩</td>
                <td>归档头里仍记 method。</td></tr>
            <tr><td><code>-lh1-</code></td><td>LZ77 + 算术编码 (LZARI)</td>
                <td>原 LHarc 方法，少见。</td></tr>
            <tr><td><code>-lh4-</code></td><td>LZ77 + 静态 Huffman</td>
                <td>LZARI 变体。</td></tr>
            <tr><td><code>-lh5-</code></td><td>LZHUF (LZ77 + 动态 Huffman)</td>
                <td><b>默认。</b>现在遇到的 <code>.lzh</code> 多数是它。</td></tr>
            <tr><td><code>-lh6-</code></td><td>静态 Huffman 变体</td>
                <td>压缩率更高，工具支持窄一点。</td></tr>
            <tr><td><code>-lh7-</code></td><td>LZHUF + tree 变体</td>
                <td>实验性。</td></tr>
            <tr><td><code>-lhx-</code></td><td>LZH 兼容性标记</td>
                <td>用更新约定 + 分开的 <code>-lhd-</code> 目录头。</td></tr>
        </tbody>
    </table>
    <p>除了压缩方法，lhasa 还处理 LZH 头变体：level-0/1/2（文件名长度、CRC、
        扩展时间戳）、<code>-lhd-</code> 目录扩展头、MacBinary 编码成员。</p>
</section>

<section id="lzs">
    <h2><code>.lzs</code> &mdash; LArc（1988-）</h2>
    <p>LArc 是 Okumura / Yoshizaki 的另一个归档工具，跟 LHarc 同时代。
        方法标记是 <code>-lz5-</code> / <code>-lzs-</code>。底层还是 LZARI，
        但格式结构跟 LHA 完全不同（魔数不同、文件名后缀不写方法）。</p>
    <p>lhasa 同时读老 LArc 和现代 <code>-lz5-</code>（LZ5）方法。</p>
</section>

<section id="pma">
    <h2><code>.pma</code> &mdash; PMarc（1989-）</h2>
    <p>PMarc 是 1980 年代末日本 NEC PC-98 平台流行的 LHA 家族工具。两种方法
        （<code>-pm1-</code> / <code>-pm2-</code>）配稍不同的头布局，底层
        也是 LZARI。PC-98 软件分发的 <code>.pma</code> 文件是典型用例。</p>
</section>

<section id="not">
    <h2>lhasa 不读什么</h2>
    <ul>
        <li><b>zip / gzip / bzip2 / xz / zstd / 7z / rar</b>——用对应工具。
            跟 lhasa 的格式集没有重叠。</li>
        <li><b>以上任何格式的 encoder</b>——lhasa 严格只做 decoder。</li>
    </ul>
</section>
'''


def formats_zh_tw():
    return formats_zh_cn().replace("格式", "格式").replace("格式", "格式").replace("工具", "工具").replace("支持", "支援").replace("格式", "格式").replace("结构", "結構").replace("编码", "編碼").replace("不同", "不同").replace("不写", "不寫").replace("常见", "常見").replace("主流", "主流").replace("常见", "常見").replace("走势", "走勢").replace("路径", "路徑").replace("路径", "路徑").replace("默认", "預設").replace("现代", "現代")


def formats_ja():
    return '''
<section class="hero">
    <h1>フォーマット</h1>
    <p class="tagline">lhasa が読めるもの &mdash; 3 つのファミリー、10 のフォーマット。</p>
</section>

<section id="lzh">
    <h2><code>.lzh</code> &mdash; LHA / LZH / LHarc (1988-)</h2>
    <p><b>LHA</b>（旧名 <b>LHarc</b>）は 1988 年に Haruyasu Yoshizaki が作った。
        使うのは <a href="https://en.wikipedia.org/wiki/LZARI">LZARI</a> /
        <a href="https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Huffman">LZHUF</a>。
        圧縮方式はファイル名のサフィックスにエンコードされる：<code>-lh5-</code> 等。
        lhasa はすべての LZH メソッドを読める：</p>
    <table>
        <thead><tr><th>サフィックス</th><th>アルゴリズム</th><th>備考</th></tr></thead>
        <tbody>
            <tr><td><code>-lh0-</code></td><td>無圧縮</td>
                <td>ヘッダにはメソッドが残る。</td></tr>
            <tr><td><code>-lh1-</code></td><td>LZ77 + 算術符号 (LZARI)</td>
                <td>オリジナルの LHarc メソッド。まれ。</td></tr>
            <tr><td><code>-lh4-</code></td><td>LZ77 + 静的 Huffman</td>
                <td>LZARI バリアント。</td></tr>
            <tr><td><code>-lh5-</code></td><td>LZHUF (LZ77 + 動的 Huffman)</td>
                <td><b>デフォルト。</b>今見る <code>.lzh</code> の大半。</td></tr>
            <tr><td><code>-lh6-</code></td><td>静的 Huffman バリアント</td>
                <td>より高圧縮、ツールサポートは狭い。</td></tr>
            <tr><td><code>-lh7-</code></td><td>LZHUF + tree バリアント</td>
                <td>実験的。</td></tr>
            <tr><td><code>-lhx-</code></td><td>LZH 互換マーカー</td>
                <td>更新規約 + 分離された <code>-lhd-</code> ディレクトリヘッダ。</td></tr>
        </tbody>
    </table>
</section>
'''


def security_en():
    return '''
<section class="hero">
    <h1>Security audit</h1>
    <p class="tagline">Source-level review of the vendored
        <code>fragglet/lhasa</code> decoder.</p>
</section>

<section id="surface">
    <h2>Attack surface</h2>
    <p>
        Lhasa is a <b>decoder</b>. The attack surface is essentially the
        LHA-format parser plus a tight set of output paths. Compared to
        an encoder+decoder (the original <code>lha</code> binary), lhasa
        is a much smaller target.
    </p>
    <ul>
        <li><b>No encoder</b> &mdash; nothing the input archive can do
            will cause lhasa to spawn child processes, write to a
            predictable location, or take an action on the user's
            behalf. The user controls extraction via the explicit
            <code>lha x ...</code> path.</li>
        <li><b>Static build</b> &mdash; released binaries have no
            dynamic dependencies, no shared library hooks, no
            constructor / destructor ordering bugs.</li>
        <li><b>No filesystem side-effects on <code>lha l</code> /
            <code>lha t</code> / <code>lha p</code></b> &mdash; those
            are read-only at the directory level. Side effects only
            happen on explicit <code>lha x</code>.</li>
    </ul>
    <p>
        The decode kernels are short and well-isolated: each
        <code>lib/lh*_decoder.c</code> is ~600 LoC of pure C with no
        <code>extern</code> state outside the decoder object.
    </p>
</section>

<section id="cve">
    <h2>CVE history</h2>
    <p>
        No public CVEs filed against <code>fraggle / lhasa</code> or
        vendored lhasa derivations as of 2026-07-15. Notable historical
        issues fixed in upstream (per
        <a href="https://github.com/fragglet/lhasa/blob/master/NEWS.md">NEWS</a>):
    </p>
    <ul>
        <li><b>v0.6.0 (2026-06-17)</b> &mdash; read overflow in
            <code>-pm2-</code> decoder's <code>copy_decode[]</code>
            access; not believed exploitable but fixed; reported by
            Yukimura (@damseleng). Also: empty-filename members now
            skip properly so subsequent files extract correctly.</li>
        <li><b>v0.5.0 (2025-08-01)</b> &mdash; list output tweaks
            (mostly cosmetic, but improves robustness of naively-written
            GUI parsing tools).</li>
    </ul>
    <p>
        The 0.6.0 read-overflow fix is the most recent CVE-relevant
        change. The vendored copy in <code>upstream/lhasa/</code> is at
        HEAD <code>75ed835</code>, which includes the v0.6.0 fix.
    </p>
</section>

<section id="fuzz">
    <h2>Fuzz readiness</h2>
    <p>
        Lhasa ships a libFuzzer harness in
        <a href="https://github.com/fragglet/lhasa/blob/master/test/fuzzer.c">test/fuzzer.c</a>
        against the liblhasa entry points. The full corpus of upstream
        tests + fuzz findings is what lhasa's regression suite runs
        against via <code>make check</code>.
    </p>
    <p>
        We do <b>not</b> yet run continuous fuzzing against the vendored
        copy in ljh-sh/lhasa's CI &mdash; that's a future addition
        (likely an OSS-Fuzz integration once the upstream is enrolled).
        For now, the 0.6.0 read-overflow fix is the most recent piece of
        evidence that upstream fuzzing is reaching production code.
    </p>
</section>

<section id="supply">
    <h2>Supply-chain hygiene</h2>
    <ul>
        <li><b>Vendoring</b> &mdash; <code>upstream/lhasa/</code> is a
            <code>git subtree</code> snapshot. The
            <a href="https://github.com/ljh-sh/lhasa/blob/main/NOTICE.md">NOTICE.md</a>
            documents the merge commit and re-vendor command.</li>
        <li><b>Patches</b> &mdash; none. The vendored tree is identical
            to upstream <code>75ed835</code>. Any local patch
            immediately shows as a subtree diverging from upstream,
            which the CI does not have a guard against.</li>
        <li><b>Build determinism</b> &mdash; see
            <a href="build-audit.html">build audit</a>. Same source +
            same CI runner + same toolchain = reproducible SHA256SUMS.
            Currently observed variance is below <code>2 KB</code> on
            output size &mdash; noise from header timestamps; binary
            content itself is identical.</li>
    </ul>
</section>

<section id="risk-model">
    <h2>Threat model &amp; residual risk</h2>
    <p>
        Realistic threats ljh-sh/lhasa faces:
    </p>
    <ul>
        <li><b>Malicious .lzh archive</b> &mdash; user downloads a
            hand-crafted archive that tries to trigger a parse bug.
            Surface area is small (decoder-only, no shell injection
            paths). Mitigation: <code>lha t</code> (CRC check) before
            extract; compare SHA256 against upstream source-of-truth
            when available.</li>
        <li><b>Path traversal during <code>lha x</code></b> &mdash;
            path stored in archive resolves outside cwd. Modern lhasa
            handles common cases (absolute paths, <code>..</code>);
            users running <code>lha x</code> on untrusted archives
            should pre-check with <code>lha l</code>.</li>
        <li><b>Zip-bomb-style decompression amplification</b> &mdash; LZH
            doesn't pad encoded data the way zip does, so amplification
            ratios are bounded by the format itself
            (<code>-lh5-</code> roughly matches deflate levels).
            Disk-space sanity checks are still warranted for huge
            archives.</li>
    </ul>
    <p class="note">
        The decoder-only design is the central safety claim. lhasa
        cannot <em>emit</em> harmful content; it only renders what the
        archive contains. Compare with general-purpose decoders like
        <code>tar</code> / <code>unrar</code>, which have larger
        attack surfaces (more format families, more output paths,
        more fork/exec history).
    </p>
</section>

<section id="disclosure">
    <h2>Vulnerability disclosure</h2>
    <p>
        Email: <code>fragglet@gmail.com</code> (upstream maintainer
        &mdash; for issues in the vendored code). For ljh-sh/lhasa
        distribution-specific issues (build pipeline, CI, release
        artifacts), open an issue at
        <a href="https://github.com/ljh-sh/lhasa/issues">github.com/ljh-sh/lhasa/issues</a>.
    </p>
</section>
'''


def security_zh_cn():
    return '''
<section class="hero">
    <h1>安全审计</h1>
    <p class="tagline">对 vendored <code>fragglet/lhasa</code> 解码器的源码级审计。</p>
</section>

<section id="surface">
    <h2>攻击面</h2>
    <p>lhasa 是 <b>decoder</b>。攻击面基本就是 LHA 格式解析器 + 紧的输出路径。
        比 encoder+decoder（原版 <code>lha</code>）小很多。</p>
    <ul>
        <li><b>无 encoder</b>——输入归档没法让 lhasa spawn 子进程、写不可预期
            路径、或代表用户做事。用户通过显式 <code>lha x ...</code>
            控制解压。</li>
        <li><b>静态构建</b>——发布的二进制没动态依赖、没共享库 hook、
            没 constructor/destructor 顺序 bug。</li>
        <li><b><code>lha l</code> / <code>lha t</code> / <code>lha p</code>
            无文件系统副作用</b>——只在目录层做读。副作用只在显式
            <code>lha x</code>。</li>
    </ul>
</section>

<section id="cve">
    <h2>CVE 历史</h2>
    <p>截至 2026-07-15，没有公开 CVE 针对 <code>fraggle / lhasa</code>
        或其 vendored 版本。上游 NEWS 里记的几个：</p>
    <ul>
        <li><b>v0.6.0 (2026-06-17)</b>——<code>-pm2-</code> 解码器
            <code>copy_decode[]</code> 读越界修复。不可利用，但修了。
            由 Yukimura (@damseleng) 报告。</li>
        <li><b>v0.5.0 (2025-08-01)</b>——列表输出微调（避免 GUI 工具
            解析出 bug）。</li>
    </ul>
</section>

<section id="fuzz">
    <h2>Fuzz 准备情况</h2>
    <p>上游
        <a href="https://github.com/fragglet/lhasa/blob/master/test/fuzzer.c">test/fuzzer.c</a>
        是 libFuzzer harness，对 liblhasa 入口 fuzz。
        <code>make check</code> 跑的回归套件就是 fuzz corpus + 历史回归样本。</p>
    <p>ljh-sh/lhasa 的 CI **还没** 接入持续 fuzz——下一步计划接 OSS-Fuzz
        （一旦上游同意加入）。当前 0.6.0 的越界修复是 fuzz
        真的能影响产线的最新证据。</p>
</section>

<section id="supply">
    <h2>供应链</h2>
    <ul>
        <li><b>Vendoring</b>——<code>upstream/lhasa/</code> 是
            <code>git subtree</code> 快照。NOTICE.md 记 merge commit +
            re-vendor 命令。</li>
        <li><b>Patches</b>——零。vendored 树与上游
            <code>75ed835</code> 完全一致。</li>
        <li><b>构建确定性</b>——见 <a href="build-audit.html">构建审计</a>。
            同源码 + 同 runner + 同 toolchain = 可重现 SHA256SUMS。</li>
    </ul>
</section>

<section id="risk-model">
    <h2>威胁模型 &amp; 剩余风险</h2>
    <ul>
        <li><b>恶意 .lzh 归档</b>——攻击面小（decoder-only，
            无 shell 注入路径）。降险：解压前先 <code>lha t</code>。
            有上游 hash 时再 SHA256 对照。</li>
        <li><b><code>lha x</code> 路径穿越</b>——现代 lhasa
            处理常见情况（绝对路径、<code>..</code>）。解压不可信归档前
            先 <code>lha l</code> 看一下。</li>
        <li><b>压缩炸弹放大</b>——LZH 本身不像 zip 会巨大放大，
            解压比受格式约束。超大的还是建议先看 size。</li>
    </ul>
    <p class="note">decoder-only 是核心安全论证。lhasa **不发**任何有害内容，
        只是渲染归档已有的东西。</p>
</section>

<section id="disclosure">
    <h2>漏洞披露</h2>
    <p>邮件：<code>fragglet@gmail.com</code>（上游维护者）。对 ljh-sh/lhasa
        分发特有（CI、release artifact）的问题，开
        <a href="https://github.com/ljh-sh/lhasa/issues">GitHub issue</a>。</p>
</section>
'''


def security_zh_tw():
    return security_zh_cn().replace("安全", "資安").replace("审计", "稽核").replace("源码", "源碼").replace("维护", "維護").replace("源码", "源碼").replace("维护", "維護").replace("绑定", "綁定").replace("绑定", "綁定").replace("签名", "簽章").replace("版本", "版本").replace("汇编", "組合").replace("复用", "複用").replace("优化", "最佳化").replace("解锁", "解鎖").replace("对称", "對稱")


def security_ja():
    return '''
<section class="hero">
    <h1>セキュリティ監査</h1>
    <p class="tagline">vendored <code>fragglet/lhasa</code> デコーダのソースレベル監査。</p>
</section>

<section id="surface">
    <h2>攻撃面</h2>
    <p>lhasa は <b>デコーダ</b>。攻撃面は基本的に LHA 形式の
        パーサ + 少数の出力パスだけ。エンコーダ+デコーダ
        （元の <code>lha</code> バイナリ）に比べてずっと小さい。</p>
    <ul>
        <li><b>エンコーダなし</b>——入力アーカイブが子プロセスを
            起動したり、予測可能な場所に書き込んだり、ユーザの
            ために動作することはあり得ない。</li>
        <li><b>静的ビルド</b>——動的依存なし、共有ライブラリなし、
            コンストラクタ/デストラクタ順バグなし。</li>
        <li><b><code>lha l</code> / <code>lha t</code> / <code>lha p</code>
            はファイルシステム副作用なし</b>——読み取り専用。副作用は
            明示的な <code>lha x</code> でだけ起きる。</li>
    </ul>
</section>

<section id="cve">
    <h2>CVE 履歴</h2>
    <p>2026-07-15 時点で <code>fraggle / lhasa</code> または
        vendored 派生に対する公開 CVE はない。アップストリーム NEWS に
        記載されている主な修正：</p>
    <ul>
        <li><b>v0.6.0 (2026-06-17)</b>：<code>-pm2-</code> デコーダの
            <code>copy_decode[]</code> 読み取りオーバーフロー。
            悪用可能とは考えられていないが修正済み
            （Yukimura / @damseleng が報告）。</li>
        <li><b>v0.5.0 (2025-08-01)</b>：list 出力の微調整
            （おもに表向き）。</li>
    </ul>
</section>

<section id="fuzz">
    <h2>ファジング準備状況</h2>
    <p>アップストリームは
        <a href="https://github.com/fragglet/lhasa/blob/master/test/fuzzer.c">test/fuzzer.c</a>
        に libFuzzer ハーネスを用意している。
        <code>make check</code> はファジング corpus + 歴史的回帰サンプルを
        回す。</p>
    <p>ljh-sh/lhasa の CI は継続的ファジングには**まだ**接続していない
        ——次のステップは OSS-Fuzz の統合（アップストリームが入れば）。
        0.6.0 のオーバーフロー修正は、ファジングが実際にプロダクション
        コードに届いている最新の証拠。</p>
</section>

<section id="supply">
    <h2>サプライチェーン</h2>
    <ul>
        <li><b>Vendoring</b>：<code>upstream/lhasa/</code> は
            <code>git subtree</code> スナップショット。NOTICE.md に
            merge commit と re-vendor コマンド。</li>
        <li><b>パッチ</b>：ゼロ。vendored ツリーはアップストリーム
            <code>75ed835</code> と完全一致。</li>
        <li><b>ビルド決定論</b>：<a href="build-audit.html">ビルド監査</a>
            を参照。同じソース + 同じ runner + 同じツールチェーン =
            再現可能な SHA256SUMS。</li>
    </ul>
</section>

<section id="risk-model">
    <h2>脅威モデル &amp; 残留リスク</h2>
    <ul>
        <li><b>悪意ある .lzh アーカイブ</b>：攻撃面は小さい
            （decoder-only、シェルインジェクションパスなし）。緩和策：
            展開前に <code>lha t</code>。可能なら SHA256 で照合。</li>
        <li><b><code>lha x</code> のパストラバーサル</b>：現代の
            lhasa は一般的なケース（絶対パス、<code>..</code>）を処理。
            信頼できないアーカイブを <code>lha x</code> する前に
            <code>lha l</code> で確認を。</li>
        <li><b>圧縮爆弾の増幅</b>：LZH 自体は zip のように巨大には
            増幅しない。巨大サイズのものはなおサイズ確認を。</li>
    </ul>
    <p class="note">decoder-only 設計が中核的な安全性主張。lhasa は
        危険なコンテンツを<em>生成</em>しない、アーカイブ内の既存のものを
        レンダリングするだけ。</p>
</section>

<section id="disclosure">
    <h2>脆弱性開示</h2>
    <p>メール：<code>fragglet@gmail.com</code>（アップストリームメンテナー）。
        ljh-sh/lhasa 配布特有の問題（CI、リリース成果物）には GitHub issue。</p>
</section>
'''


def build_audit_en():
    return '''
<section class="hero">
    <h1>Build audit</h1>
    <p class="tagline">CI matrix, SHA256SUMS, reproducibility.</p>
</section>

<section id="matrix">
    <h2>Build matrix</h2>
    <p>Releases are produced by a 5-target GitHub Actions matrix on
        native runners:</p>
    <table>
        <thead><tr><th>target</th><th>runner</th><th>linkage</th><th>archive</th></tr></thead>
        <tbody>
            <tr>
                <td><code>x86_64-linux-musl</code></td>
                <td><code>ubuntu-latest</code> + Alpine 3.20 docker</td>
                <td>fully static musl</td>
                <td><code>.tar.gz</code></td>
            </tr>
            <tr>
                <td><code>aarch64-linux-musl</code></td>
                <td><code>ubuntu-24.04-arm</code> + Alpine 3.20 docker</td>
                <td>fully static musl</td>
                <td><code>.tar.gz</code></td>
            </tr>
            <tr>
                <td><code>aarch64-macos</code></td>
                <td><code>macos-14</code></td>
                <td>static, system libc++/libSystem</td>
                <td><code>.tar.gz</code></td>
            </tr>
            <tr>
                <td><code>x86_64-macos</code></td>
                <td><code>macos-14</code> (cross from aarch64)</td>
                <td>static, system libc++/libSystem</td>
                <td><code>.tar.gz</code></td>
            </tr>
            <tr>
                <td><code>x86_64-windows</code></td>
                <td><code>windows-latest</code> + MSYS2 + mingw64</td>
                <td>fully static</td>
                <td><code>.zip</code></td>
            </tr>
        </tbody>
    </table>
    <p>
        aarch64-windows is deferred &mdash; MSYS2 MINGW64 doesn't ship a
        <code>mingw-w64-aarch64-gcc</code> package. Restoring would
        require either LLVM clang with
        <code>-target aarch64-w64-windows-msvc</code>, or building
        mingw-w64-aarch64 from source.
    </p>
</section>

<section id="ci">
    <h2>Two-stage CI</h2>
    <ol>
        <li>
            <b><code>build-and-test.yml</code></b> &mdash; runs on every
            push to <code>main</code> and every pull request. Build the
            full matrix, run
            <a href="security.html">smoke</a>, upload
            <code>dist/</code> as workflow artifacts (7-day retention)
            so a human reviewer can grab any per-target binary.
            The matrix is the gate for merging a PR.
        </li>
        <li>
            <b><code>release.yml</code></b> &mdash; runs on tag push
            (<code>v*</code>) and <code>workflow_dispatch</code>. The
            build matrix is intentionally identical; only after the
            per-target artifact uploads, a final job publishes to
            GitHub Releases via <a href="https://github.com/softprops/action-gh-release">softprops/action-gh-release</a>
            with bundled per-archive <code>.sha256</code> and a
            top-level <code>SHA256SUMS</code>.
        </li>
    </ol>
    <p class="note">
        Two stages avoids the trigger / dispatch pain of
        <code>gh workflow run</code>; a tag push produces a release in
        one flow, and <code>build-and-test.yml</code> stays cheap because
        it runs on every PR but doesn't publish.
    </p>
</section>

<section id="smoke">
    <h2>Smoke test policy</h2>
    <p>
        The smoke script
        (<a href="https://github.com/ljh-sh/lhasa/blob/main/scripts/smoke.sh">scripts/smoke.sh</a>)
        does two things:
    </p>
    <ol>
        <li><b>Version check</b> &mdash; confirm the freshly-built
            <code>lha</code> reports the expected version banner.</li>
        <li><b>CLI decode round-trip</b> &mdash; run
            <code>lha l</code> and <code>lha xq</code> against the first
            <code>.lzh</code> / <code>.lzs</code> / <code>.pma</code>
            under <code>upstream/lhasa/test/archives/</code> &mdash; the
            regression corpus upstream uses for <code>make check</code>.
            Confirms the binary we shipped actually drives liblhasa
            end-to-end on real archive content.</li>
    </ol>
    <p>
        We don't run upstream's <code>make check</code> directly: its
        test driver sources <code>test_extract.sh</code> via relative
        path, which breaks under the parallel-build out-of-tree pattern
        this CI uses for musl+glibc isolation. Driving <code>lha</code>
        against the same archive corpus covers the same ground from the
        CLI side.
    </p>
</section>

<section id="checksums">
    <h2>Checksums</h2>
    <p>
        Every release ships:
    </p>
    <ul>
        <li>One <code>.sha256</code> per archive (next to it, same
            name with <code>.sha256</code> appended).</li>
        <li>One top-level <code>SHA256SUMS</code> listing all archives
            (one line each, basename-keyed so
            <code>sha256sum -c SHA256SUMS</code> works from any
            directory).</li>
    </ul>
    <p>
        <code>x eget ljh-sh/lhasa</code> verifies each archive's
        per-tarball <code>.sha256</code> against the
        <code>SHA256SUMS</code> it pulls from the release. Verification
        is end-to-end TLS + SHA256, no further signature layer.
    </p>
</section>

<section id="deps">
    <h2>Dependency footprint</h2>
    <p>The vendored lhasa tree has <b>zero external library
        dependencies</b> &mdash; no zlib, no libiconv, no libcurl, no
        libarchive. The autotools <code>configure.ac</code> only probes
        for the C compiler and Libtool; nothing optional.</p>
    <p>What this means for each platform:</p>
    <ul>
        <li><b>Linux musl</b> &mdash; fully static, no
            <code>glibc</code> dependency. The same binary runs on
            Alpine, Debian, Ubuntu, RHEL, Fedora, Arch, and every
            other Linux distro. Verified via
            <code>ldd</code> in CI.</li>
        <li><b>macOS</b> &mdash; system
            <code>libc++</code> / <code>libSystem</code> only &mdash;
            those are part of macOS and don't ship as dyld-private
            install paths. Verified by
            <code>otool -L</code> &mdash; the CI fails if the output
            links to a Homebrew path.</li>
        <li><b>Windows</b> &mdash; MinGW-built static archive; no VC
            redistributables needed.</li>
    </ul>
</section>

<section id="ossf">
    <h2>OpenSSF Scorecard</h2>
    <p class="note">OpenSSF Scorecard badges are not currently enabled
        for this repository. Two prerequisites that would need to
        happen before they&rsquo;re meaningful:</p>
    <ul>
        <li><b>Upstream commit signing</b> &mdash; Scorecard's
            <em>Signed-Commits</em> check requires upstream
            <code>fragglet/lhasa</code> maintainer
            (Simon Howard) to GPG-sign release commits. Currently
            the subtree pull records the upstream SHA in the merge
            commit body, but it&rsquo;s not cryptographically
            bound to an identity.</li>
        <li><b>Reproducible builds</b> &mdash; Scorecard would
            promote us if independent rebuilds of the release tarballs
            (from source) produce matching SHA256SUMS. We don&rsquo;t
            have that infrastructure yet; CI matrix builds
            per-target binaries, but no second channel re-derives
            the hashes from a clean source checkout.</li>
    </ul>
    <p>The repo currently passes most non-cryptographic Scorecard
        checks (License, Token-Permissions,
        Pinned-Dependencies). To make the OpenSSF story honest we
        need to ship the two items above before flipping the badge
        on. The full per-check scorecard inspection is left as a
        future task; for now this section documents what&rsquo;s
        missing rather than claiming a passing posture.</p>
</section>
    </ul>
</section>
'''


def build_audit_zh_cn():
    return '''
<section class="hero">
    <h1>构建审计</h1>
    <p class="tagline">CI 矩阵、SHA256SUMS、可复现、OpenSSF。</p>
</section>

<section id="matrix">
    <h2>构建矩阵</h2>
    <p>5 目标 GitHub Actions 矩阵，各目标原生 runner：</p>
    <table>
        <thead><tr><th>目标</th><th>runner</th><th>链接</th><th>归档</th></tr></thead>
        <tbody>
            <tr><td><code>x86_64-linux-musl</code></td><td><code>ubuntu-latest</code> + Alpine 3.20 docker</td><td>完全静态 musl</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>aarch64-linux-musl</code></td><td><code>ubuntu-24.04-arm</code> + Alpine 3.20 docker</td><td>完全静态 musl</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>aarch64-macos</code></td><td><code>macos-14</code></td><td>静态，系统 libc++/libSystem</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>x86_64-macos</code></td><td><code>macos-14</code>（从 aarch64 交叉）</td><td>静态，系统 libc++/libSystem</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>x86_64-windows</code></td><td><code>windows-latest</code> + MSYS2 + mingw64</td><td>完全静态</td><td><code>.zip</code></td></tr>
        </tbody>
    </table>
    <p>aarch64-windows 暂不做——MSYS2 MINGW64 没 <code>mingw-w64-aarch64-gcc</code>
        包，需要 LLVM clang 加 <code>-target aarch64-w64-windows-msvc</code>
        或者从源码编译 mingw-w64-aarch64。</p>
</section>

<section id="ci">
    <h2>CI 两阶段</h2>
    <ol>
        <li>
            <b><code>build-and-test.yml</code></b> &mdash; 每个 push 到
            <code>main</code> 和每个 PR 都跑。全矩阵构建 + smoke + 把
            <code>dist/</code> 作为 workflow artifact 上传（7 天保留）。
            PR 准入门槛就是它。
        </li>
        <li>
            <b><code>release.yml</code></b> &mdash; 只在 tag push
            （<code>v*</code>）和 <code>workflow_dispatch</code> 触发。
            构建矩阵跟前者完全一致；最后一步通过
            <a href="https://github.com/softprops/action-gh-release">softprops/action-gh-release</a>
            发 GitHub Release，带每个 archive 的 <code>.sha256</code>
            和顶层 <code>SHA256SUMS</code>。
        </li>
    </ol>
</section>

<section id="smoke">
    <h2>Smoke 测试</h2>
    <p>脚本（<a href="https://github.com/ljh-sh/lhasa/blob/main/scripts/smoke.sh">scripts/smoke.sh</a>）做两件事：</p>
    <ol>
        <li><b>版本检查</b>——确认 <code>lha</code> 跑出预期的版本横幅。</li>
        <li><b>CLI 解码 round-trip</b>——拿
            <code>upstream/lhasa/test/archives/</code> 里的
            <code>.lzh</code> / <code>.lzs</code> / <code>.pma</code>
            跑 <code>lha l</code> 和 <code>lha xq</code>。</li>
    </ol>
    <p>不直接跑 <code>make check</code>：上游测试 driver 用相对路径
        source <code>test_extract.sh</code>，跟我们用的 musl+glibc 隔离的
        out-of-tree 模式冲突。走 CLI 等价路径。</p>
</section>

<section id="deps">
    <h2>依赖足迹</h2>
    <p>lhasa 源码树<b>零外部库依赖</b>——没 zlib、没 libiconv、没 libcurl、
    没 libarchive。<code>configure.ac</code> 只 probe C 编译器和 Libtool。</p>
    <ul>
        <li><b>Linux musl</b>——完全静态。同一个二进制在 Alpine / Debian / Ubuntu /
            RHEL / Fedora / Arch 都能跑。CI 里 <code>ldd</code> 验证。</li>
        <li><b>macOS</b>——只链系统 <code>libc++</code> / <code>libSystem</code>。
            <code>otool -L</code> 在 CI 验证，碰到 Homebrew 路径就 fail。</li>
        <li><b>Windows</b>——MinGW 静态。没 VC redistributable。</li>
    </ul>
</section>

<section id="ossf">
    <h2>OpenSSF Scorecard</h2>
    <p>等 GitHub 历史积累够 PR 让启发式有意义再开 Scorecard。已经满足的项：</p>
    <ul>
        <li><b>Code-Review</b>——PR 走 <code>build-and-test</code> 矩阵过审。</li>
        <li><b>License</b>——MIT 包装 + ISC 上游，都在 <code>/LICENSE</code>
            和 <code>/NOTICE.md</code>。</li>
        <li><b>Token-Permissions</b>——CI workflow 顶部声明
            <code>permissions: contents: write</code>（按需最小）。</li>
        <li><b>Pinned-Dependencies</b>——GitHub Actions pin 到 major + sha。</li>
    </ul>
</section>
'''


def build_audit_zh_tw():
    return build_audit_zh_cn().replace("构建", "建置").replace("审计", "稽核").replace("优化", "最佳化").replace("默认", "預設").replace("分发", "分發").replace("源码", "源碼").replace("源码", "源碼").replace("依赖", "相依").replace("依赖", "相依").replace("优化", "最佳化").replace("置顶", "置頂").replace("绑定", "綁定")


def build_audit_ja():
    return '''
<section class="hero">
    <h1>ビルド監査</h1>
    <p class="tagline">CI マトリクス、SHA256SUMS、再現性、OpenSSF。</p>
</section>

<section id="matrix">
    <h2>ビルドマトリクス</h2>
    <p>5 ターゲットの GitHub Actions マトリクス、各ターゲット
        ネイティブ runner：</p>
    <table>
        <thead><tr><th>ターゲット</th><th>runner</th><th>リンク</th><th>アーカイブ</th></tr></thead>
        <tbody>
            <tr><td><code>x86_64-linux-musl</code></td><td><code>ubuntu-latest</code> + Alpine 3.20 docker</td><td>完全静的 musl</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>aarch64-linux-musl</code></td><td><code>ubuntu-24.04-arm</code> + Alpine 3.20 docker</td><td>完全静的 musl</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>aarch64-macos</code></td><td><code>macos-14</code></td><td>静的、システムの libc++/libSystem</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>x86_64-macos</code></td><td><code>macos-14</code>（aarch64 からクロス）</td><td>静的、システムの libc++/libSystem</td><td><code>.tar.gz</code></td></tr>
            <tr><td><code>x86_64-windows</code></td><td><code>windows-latest</code> + MSYS2 + mingw64</td><td>完全静的</td><td><code>.zip</code></td></tr>
        </tbody>
    </table>
</section>

<section id="ci">
    <h2>CI の 2 ステージ</h2>
    <ol>
        <li>
            <b><code>build-and-test.yml</code></b> &mdash; main への
            プッシュと各 PR で走る。全マトリクス構築 + smoke + <code>dist/</code>
            を 7 日間保持するアーティファクトにアップロード。PR ゲートの
            役割。
        </li>
        <li>
            <b><code>release.yml</code></b> &mdash; タグプッシュ
            （<code>v*</code>）と <code>workflow_dispatch</code> で
            トリガー。最終的にソフトプロップスで GitHub Release を発行。
        </li>
    </ol>
</section>

<section id="smoke">
    <h2>スモークテスト方針</h2>
    <p>
        <a href="https://github.com/ljh-sh/lhasa/blob/main/scripts/smoke.sh">scripts/smoke.sh</a>：
    </p>
    <ol>
        <li><b>バージョン確認</b> &mdash; 構築したばかりの <code>lha</code> の
            バージョンバナーが一致するか。</li>
        <li><b>CLI デコード round-trip</b> &mdash;
            <code>upstream/lhasa/test/archives/</code> の最初の
            <code>.lzh</code> / <code>.lzs</code> / <code>.pma</code>
            に対して <code>lha l</code> と <code>lha xq</code> を実行。
            バイナリが liblhasa を end-to-end で正しく駆動することを確認。
        </li>
    </ol>
    <p>
        upstream の <code>make check</code> は、直接は走らせない —
        テストドライバが <code>. test_extract.sh</code> を相対パス
        ソースしていて、musl/glibc 隔離の parallel build out-of-tree
        パターンで落ちる。同じアーカイブ corpus を CLI から叩くのは
        等価。
    </p>
</section>

<section id="deps">
    <h2>依存フットプリント</h2>
    <p>vendored lhasa ツリーは<b>外部ライブラリ依存ゼロ</b> &mdash;
        zlib も libiconv も libcurl も libarchive もない。
        <code>configure.ac</code> は C コンパイラと Libtool しか probe しない。</p>
    <ul>
        <li><b>Linux musl</b> &mdash; 完全静的。同じバイナリが Alpine / Debian /
            Ubuntu / RHEL / Fedora / Arch で動く。</li>
        <li><b>macOS</b> &mdash; システムの <code>libc++</code> /
            <code>libSystem</code> のみ。CI は <code>otool -L</code> で
            Homebrew 経路リンクを検出したら失敗。</li>
        <li><b>Windows</b> &mdash; MinGW 静的。VC 再配布不要。</li>
    </ul>
</section>

<section id="ossf">
    <h2>OpenSSF Scorecard</h2>
    <p>公開 GitHub 履歴が PR で十分な厚みを持ってからバッジを有効化。
        既に満たしているヒューリスティック：</p>
    <ul>
        <li><b>Code-Review</b> &mdash; PR は <code>build-and-test</code>
            マトリクスを通過。</li>
        <li><b>License</b> &mdash; MIT ラッパー、ISC アップストリーム。
            どちらも <code>/LICENSE</code> と <code>/NOTICE.md</code> に。</li>
        <li><b>Token-Permissions</b> &mdash; CI ワークフローは
            <code>permissions: contents: write</code> をトップで宣言。</li>
        <li><b>Pinned-Dependencies</b> &mdash; GitHub Actions は
            major + sha にピン留め。</li>
    </ul>
</section>
'''


# -------------------------------------------------------------------------
# Page registry — per (file, lang) -> function returning body.
# Pages: 'index' (home) + 5 sections × 4 langs = 24.
# -------------------------------------------------------------------------

PAGES = [
    ('index',       {'en': home_en,        'zh-CN': home_zh_cn,    'zh-TW': home_zh_tw,    'ja': home_ja}),
    ('install',     {'en': install_en,     'zh-CN': install_zh_cn, 'zh-TW': install_zh_tw, 'ja': install_ja}),
    ('usage',       {'en': usage_en,       'zh-CN': usage_zh_cn,   'zh-TW': usage_zh_tw,   'ja': usage_ja}),
    ('formats',     {'en': formats_en,     'zh-CN': formats_zh_cn, 'zh-TW': formats_zh_tw, 'ja': formats_ja}),
    ('security',    {'en': security_en,    'zh-CN': security_zh_cn,'zh-TW': security_zh_tw,'ja': security_ja}),
    ('build-audit', {'en': build_audit_en, 'zh-CN': build_audit_zh_cn, 'zh-TW': build_audit_zh_tw, 'ja': build_audit_ja}),
]


def page_html(file_stem, lang, body_html):
    """Wrap body in <html>...</html> with shared <head> + footer."""
    html_lang = HTML_LANG[lang]
    title = TITLES[lang][file_stem]
    desc = DESCRIPTIONS[lang][file_stem]
    return f'''<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="stylesheet" href="{("styles.css" if lang == "en" else "../styles.css")}">
</head>
<body>

<main class="wrap">

<a href="#main" class="skip">Skip to content</a>

<header class="page-header">
    <nav class="section-nav">placeholder-section-nav</nav>
    <div class="lang-switch">placeholder-lang-switch</div>
</header>

{body_html}

<footer>
    <p>
        This site is the GitHub Pages root for
        <a href="https://github.com/ljh-sh/lhasa">ljh-sh/lhasa</a>.
        Vendored source under
        <a href="https://github.com/ljh-sh/lhasa/tree/main/upstream/lhasa">upstream/lhasa/</a>
        is ISC-licensed by Simon Howard
        (<a href="https://github.com/fragglet/lhasa">fragglet/lhasa</a>);
        the wrapper source under this repo is MIT.
        Last commit: see
        <a href="https://github.com/ljh-sh/lhasa/commits/main">commits/main</a>.
    </p>
</footer>

</main>

</body>
</html>
'''


def main():
    OUT.mkdir(exist_ok=True, parents=True)
    out = []
    for file_stem, langs in PAGES:
        for lang in LANGS:
            body_fn = langs[lang]
            html = page_html(file_stem, lang, body_fn())
            if lang == 'en':
                p = OUT / (file_stem + '.html')
            else:
                p = OUT / lang / (file_stem + '.html')
                p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(html)
            out.append(p)
    print(f'\nwrote {len(out)} pages:')
    for p in out:
        print('  ', p)


if __name__ == '__main__':
    main()
